unit vulkan.tutorial;

{$mode objfpc}{$H+}
{$modeswitch advancedrecords}
{$modeswitch typehelpers}

{$A8}// alignment
{$Q+}// overflow checking (opzionale)
{$R+}// range checking (opzionale)
{$D+}// debug info


interface

uses
  {$IFDEF WINDOWS}  windows,{$endif}  Classes, SysUtils, StrUtils, Generics.Collections, pax.vulkan, pax.vulkan.helpers, logger;

type
  TVec2 = record
    x, y: single;

    // Costruttori / helper (opzionale ma molto comodo)
    class function Create(const ax, ay: single): TVec2; static; inline;
    class function Zero: TVec2; static; inline;

    // Operatori matematici base
    class operator +(const a, b: TVec2): TVec2;
    class operator -(const a, b: TVec2): TVec2;
    class operator *(const v: TVec2; s: single): TVec2;
    class operator *(const a, b: TVec2): TVec2;     // component-wise multiply
    class operator /(const v: TVec2; s: single): TVec2;
    class operator -(const v: TVec2): TVec2;       // unary minus

    // Metodi di utilità geometrica
    function Length: single; inline;
    function LengthSquared: single; inline;
    function Normalized: TVec2;
    function Dot(const other: TVec2): single; inline;
    function Perpendicular: TVec2; inline;          // ruota di 90° (clockwise)
    function ToString: string;
  end;

  { TVec3 }

  TVec3 = record
    x, y, z: single;
    class function Create(const ax, ay, az: single): TVec3; static; inline;
    class operator +(const a, b: TVec3): TVec3;
    class operator -(const a, b: TVec3): TVec3;
    class operator *(const v: TVec3; s: single): TVec3;
  end;

  TVertex = record
    pos: TVec2;
    color: TVec3;
  end;

  { TVec4 }

  TVec4 = record
    x, y, z, w: single;
  end;

  { TMat4 - colonna-major (come GLM / Vulkan / OpenGL) }

  TMat4 = record
  public
    m: array[0..3, 0..3] of single;
  public
    // Moltiplicazione tra due matrici
    class operator *(const a, b: TMat4): TMat4;

    // Moltiplicazione matrice × vettore
    class operator *(const mat: TMat4; const v: TVec4): TVec4;

    function Element(row, col: integer): single; inline;
    procedure SetElement(row, col: integer; Value: single); inline;

    function ToString: string;
  end;

  TMat4Array = array of TMat4;

  { IVulkanTutorial }

  IVulkanTutorial = interface
    ['{969CB0F8-0C9B-4B0F-B377-42F20F096716}']
    function GetCaption: string;
    function getLogger: TLogger;
    procedure run;
    function GetEnableValidationLayers: boolean;
    procedure SetEnableValidationLayers(AValue: boolean);
    property EnableValidationLayers: boolean read GetEnableValidationLayers write SetEnableValidationLayers;
    property Logger: TLogger read getLogger;
    property Caption: string read GetCaption;
  end;

  { TStringArrayTypeHelper }

  TStringArrayTypeHelper = type helper for TStringArray
    function toPPChar: PPChar;
    function Text: string;
    function formattedString(): string;
  end;

  { TPPCharHelper }

  TPPCharHelper = type helper for PPChar
    function toArray(): TStringArray;
    function toArray(size: uint32): TStringArray;
  end;

  { TVulkanTutorial }

  TVulkanTutorial = class(TInterfacedObject, IVulkanTutorial)
  protected
    FEnableValidationLayers: boolean;
    FCaption: string;
    FInstanceExtensions: TStringList;
    FDeviceExtensions: TStringList;
    FDeviceFeatures: TStringList;
    procedure SetCaption(AValue: string);
  protected
    procedure InitWindow; virtual; abstract;
    procedure InitVulkan; virtual; abstract;
    procedure MainLoop; virtual; abstract;
    procedure Cleanup; virtual; abstract;
  protected
    function getLogger: TLogger;
    function GetCaption: string;
  public
    constructor Create; virtual;
    destructor Destroy; override;
    procedure run; virtual;
    function GetEnableValidationLayers: boolean;
    procedure SetEnableValidationLayers(AValue: boolean);
    property EnableValidationLayers: boolean read GetEnableValidationLayers write SetEnableValidationLayers;
    property Caption: string read GetCaption write SetCaption;
  end;



type
  TUniformBufferObject = record
    model: TMat4;
    view: TMat4;
    proj: TMat4;
  end;


const
  Pi = 3.14159265358979323846;
  TwoPi = 2 * Pi;
  HalfPi = Pi / 2;
  DegToRad = Pi / 180;
  RadToDeg = 180 / Pi;

  // ============================================================================
  // Funzioni matriciali stile GLM
  // ============================================================================

function Vec2(const x, y: single): TVec2; inline;
function Vec3(const x, y, z: single): TVec3; inline;
function Vec4(const x, y, z, w: single): TVec4; inline;

function Mat4Identity: TMat4;
function Mat4Translate(const m: TMat4; const v: TVec3): TMat4;
function Mat4Rotate(const m: TMat4; angleRad: single; const axis: TVec3): TMat4;
function Mat4Scale(const m: TMat4; const v: TVec3): TMat4;

function Mat4Perspective(fovyDeg: single; aspect: single; zNear, zFar: single): TMat4;
function Mat4LookAt(const eye, center, up: TVec3): TMat4;


operator := (ptr: Pointer): QWord;
operator := (num: QWord): Pointer;
operator <>(num: QWord; ptr: Pointer): boolean;
operator := (ai: VkApplicationInfo): string;
operator := (ici: VkInstanceCreateInfo): string;
operator := (sa: TStringArray): PPChar;
operator := (aResult: VkResult): string;
operator := (aFormat: VkFormat): string;

operator := (sa: TStringArray): string;
operator := (sType: VkStructureType): string; inline;
operator := (ptr: Pointer): string; inline;

function IfThen(val: boolean; const iftrue: string; const iffalse: string): string; inline; overload;

function PtrToHex(p: Pointer): string;
function PtrUIntToHex(p: Pointer): string;
function PtrToHexClean(p: Pointer): string;
function PtrToHexShort(p: Pointer): string;
function PtrToHexEx(p: Pointer; Digits: integer = 16): string;

implementation

uses
  syncobjs,
  typinfo,
  Math,
  LineInfo;

var
  TutorialLogger: TLogger;

operator := (ptr: Pointer): string;
begin
  if ptr = nil then
    Result := 'NIL'
  else
    Result := Format('0x%.16x', [PtrInt(ptr)]);
end;

operator := (aResult: VkResult): string;
begin
  Result := GetEnumName(TypeInfo(VkResult), Ord(aResult));
end;

operator := (aFormat: VkFormat): string;
begin
  Result := GetEnumName(TypeInfo(VkFormat), Ord(aFormat));
end;

operator := (sType: VkStructureType): string;
begin
  case sType of
    VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_TRIANGLES_DISPLACEMENT_MICROMAP_NV: Result := 'VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_TRIANGLES_DISPLACEMENT_MICROMAP_NV';
    VK_STRUCTURE_TYPE_APPLICATION_INFO: Result := 'VK_STRUCTURE_TYPE_APPLICATION_INFO';
    VK_STRUCTURE_TYPE_ATTACHMENT_DESCRIPTION_2: Result := 'VK_STRUCTURE_TYPE_ATTACHMENT_DESCRIPTION_2';
    VK_STRUCTURE_TYPE_ATTACHMENT_DESCRIPTION_STENCIL_LAYOUT: Result := 'VK_STRUCTURE_TYPE_ATTACHMENT_DESCRIPTION_STENCIL_LAYOUT';
    VK_STRUCTURE_TYPE_ATTACHMENT_FEEDBACK_LOOP_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_ATTACHMENT_FEEDBACK_LOOP_INFO_EXT';
    VK_STRUCTURE_TYPE_ATTACHMENT_REFERENCE_2: Result := 'VK_STRUCTURE_TYPE_ATTACHMENT_REFERENCE_2';
    VK_STRUCTURE_TYPE_ATTACHMENT_REFERENCE_STENCIL_LAYOUT: Result := 'VK_STRUCTURE_TYPE_ATTACHMENT_REFERENCE_STENCIL_LAYOUT';
    VK_STRUCTURE_TYPE_BEGIN_CUSTOM_RESOLVE_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_BEGIN_CUSTOM_RESOLVE_INFO_EXT';
    VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO: Result := 'VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO';
    VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_INFO: Result := 'VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_INFO';
    VK_STRUCTURE_TYPE_BIND_DATA_GRAPH_PIPELINE_SESSION_MEMORY_INFO_ARM: Result := 'VK_STRUCTURE_TYPE_BIND_DATA_GRAPH_PIPELINE_SESSION_MEMORY_INFO_ARM';
    VK_STRUCTURE_TYPE_BIND_DESCRIPTOR_BUFFER_EMBEDDED_SAMPLERS_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_BIND_DESCRIPTOR_BUFFER_EMBEDDED_SAMPLERS_INFO_EXT';
    VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO: Result := 'VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO';
    VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_INFO: Result := 'VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_INFO';
    VK_STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO: Result := 'VK_STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO';
    VK_STRUCTURE_TYPE_BIND_MEMORY_STATUS: Result := 'VK_STRUCTURE_TYPE_BIND_MEMORY_STATUS';
    VK_STRUCTURE_TYPE_BIND_SPARSE_INFO: Result := 'VK_STRUCTURE_TYPE_BIND_SPARSE_INFO';
    VK_STRUCTURE_TYPE_BLIT_IMAGE_CUBIC_WEIGHTS_INFO_QCOM: Result := 'VK_STRUCTURE_TYPE_BLIT_IMAGE_CUBIC_WEIGHTS_INFO_QCOM';
    VK_STRUCTURE_TYPE_BLIT_IMAGE_INFO_2: Result := 'VK_STRUCTURE_TYPE_BLIT_IMAGE_INFO_2';
    VK_STRUCTURE_TYPE_BUFFER_COPY_2: Result := 'VK_STRUCTURE_TYPE_BUFFER_COPY_2';
    VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO';
    VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO: Result := 'VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO';
    VK_STRUCTURE_TYPE_BUFFER_IMAGE_COPY_2: Result := 'VK_STRUCTURE_TYPE_BUFFER_IMAGE_COPY_2';
    VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER: Result := 'VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER';
    VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER_2: Result := 'VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER_2';
    VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2: Result := 'VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2';
    VK_STRUCTURE_TYPE_BUFFER_OPAQUE_CAPTURE_ADDRESS_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_BUFFER_OPAQUE_CAPTURE_ADDRESS_CREATE_INFO';
    VK_STRUCTURE_TYPE_BUFFER_USAGE_FLAGS_2_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_BUFFER_USAGE_FLAGS_2_CREATE_INFO';
    VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO';
    VK_STRUCTURE_TYPE_CALIBRATED_TIMESTAMP_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_CALIBRATED_TIMESTAMP_INFO_KHR';
    VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO: Result := 'VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO';
    VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO: Result := 'VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO';
    VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO: Result := 'VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO';
    VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_RENDERING_INFO: Result := 'VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_RENDERING_INFO';
    VK_STRUCTURE_TYPE_COMMAND_BUFFER_SUBMIT_INFO: Result := 'VK_STRUCTURE_TYPE_COMMAND_BUFFER_SUBMIT_INFO';
    VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO';
    VK_STRUCTURE_TYPE_COMPUTE_OCCUPANCY_PRIORITY_PARAMETERS_NV: Result := 'VK_STRUCTURE_TYPE_COMPUTE_OCCUPANCY_PRIORITY_PARAMETERS_NV';
    VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO';
    VK_STRUCTURE_TYPE_COOPERATIVE_MATRIX_FLEXIBLE_DIMENSIONS_PROPERTIES_NV: Result := 'VK_STRUCTURE_TYPE_COOPERATIVE_MATRIX_FLEXIBLE_DIMENSIONS_PROPERTIES_NV';
    VK_STRUCTURE_TYPE_COOPERATIVE_MATRIX_PROPERTIES_KHR: Result := 'VK_STRUCTURE_TYPE_COOPERATIVE_MATRIX_PROPERTIES_KHR';
    VK_STRUCTURE_TYPE_COPY_BUFFER_INFO_2: Result := 'VK_STRUCTURE_TYPE_COPY_BUFFER_INFO_2';
    VK_STRUCTURE_TYPE_COPY_BUFFER_TO_IMAGE_INFO_2: Result := 'VK_STRUCTURE_TYPE_COPY_BUFFER_TO_IMAGE_INFO_2';
    VK_STRUCTURE_TYPE_COPY_DESCRIPTOR_SET: Result := 'VK_STRUCTURE_TYPE_COPY_DESCRIPTOR_SET';
    VK_STRUCTURE_TYPE_COPY_IMAGE_INFO_2: Result := 'VK_STRUCTURE_TYPE_COPY_IMAGE_INFO_2';
    VK_STRUCTURE_TYPE_COPY_IMAGE_TO_BUFFER_INFO_2: Result := 'VK_STRUCTURE_TYPE_COPY_IMAGE_TO_BUFFER_INFO_2';
    VK_STRUCTURE_TYPE_COPY_IMAGE_TO_IMAGE_INFO: Result := 'VK_STRUCTURE_TYPE_COPY_IMAGE_TO_IMAGE_INFO';
    VK_STRUCTURE_TYPE_COPY_IMAGE_TO_MEMORY_INFO: Result := 'VK_STRUCTURE_TYPE_COPY_IMAGE_TO_MEMORY_INFO';
    VK_STRUCTURE_TYPE_COPY_MEMORY_INDIRECT_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_COPY_MEMORY_INDIRECT_INFO_KHR';
    VK_STRUCTURE_TYPE_COPY_MEMORY_TO_IMAGE_INDIRECT_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_COPY_MEMORY_TO_IMAGE_INDIRECT_INFO_KHR';
    VK_STRUCTURE_TYPE_COPY_MEMORY_TO_IMAGE_INFO: Result := 'VK_STRUCTURE_TYPE_COPY_MEMORY_TO_IMAGE_INFO';
    VK_STRUCTURE_TYPE_CUSTOM_RESOLVE_CREATE_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_CUSTOM_RESOLVE_CREATE_INFO_EXT';
    VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_BUILTIN_MODEL_CREATE_INFO_QCOM: Result := 'VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_BUILTIN_MODEL_CREATE_INFO_QCOM';
    VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_COMPILER_CONTROL_CREATE_INFO_ARM: Result := 'VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_COMPILER_CONTROL_CREATE_INFO_ARM';
    VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_CONSTANT_ARM: Result := 'VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_CONSTANT_ARM';
    VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_CONSTANT_TENSOR_SEMI_STRUCTURED_SPARSITY_INFO_ARM: Result := 'VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_CONSTANT_TENSOR_SEMI_STRUCTURED_SPARSITY_INFO_ARM';
    VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_CREATE_INFO_ARM: Result := 'VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_CREATE_INFO_ARM';
    VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_DISPATCH_INFO_ARM: Result := 'VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_DISPATCH_INFO_ARM';
    VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_IDENTIFIER_CREATE_INFO_ARM: Result := 'VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_IDENTIFIER_CREATE_INFO_ARM';
    VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_INFO_ARM: Result := 'VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_INFO_ARM';
    VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_PROPERTY_QUERY_RESULT_ARM: Result := 'VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_PROPERTY_QUERY_RESULT_ARM';
    VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_RESOURCE_INFO_ARM: Result := 'VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_RESOURCE_INFO_ARM';
    VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_SESSION_BIND_POINT_REQUIREMENT_ARM: Result := 'VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_SESSION_BIND_POINT_REQUIREMENT_ARM';
    VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_SESSION_BIND_POINT_REQUIREMENTS_INFO_ARM: Result := 'VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_SESSION_BIND_POINT_REQUIREMENTS_INFO_ARM';
    VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_SESSION_CREATE_INFO_ARM: Result := 'VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_SESSION_CREATE_INFO_ARM';
    VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_SESSION_MEMORY_REQUIREMENTS_INFO_ARM: Result := 'VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_SESSION_MEMORY_REQUIREMENTS_INFO_ARM';
    VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_SHADER_MODULE_CREATE_INFO_ARM: Result := 'VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_SHADER_MODULE_CREATE_INFO_ARM';
    VK_STRUCTURE_TYPE_DATA_GRAPH_PROCESSING_ENGINE_CREATE_INFO_ARM: Result := 'VK_STRUCTURE_TYPE_DATA_GRAPH_PROCESSING_ENGINE_CREATE_INFO_ARM';
    VK_STRUCTURE_TYPE_DECOMPRESS_MEMORY_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_DECOMPRESS_MEMORY_INFO_EXT';
    VK_STRUCTURE_TYPE_DEPENDENCY_INFO: Result := 'VK_STRUCTURE_TYPE_DEPENDENCY_INFO';
    VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO';
    VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_INLINE_UNIFORM_BLOCK_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_INLINE_UNIFORM_BLOCK_CREATE_INFO';
    VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO: Result := 'VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO';
    VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO';
    VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO';
    VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_SUPPORT: Result := 'VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_SUPPORT';
    VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_ALLOCATE_INFO: Result := 'VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_ALLOCATE_INFO';
    VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT: Result := 'VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT';
    VK_STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO';
    VK_STRUCTURE_TYPE_DEVICE_BUFFER_MEMORY_REQUIREMENTS: Result := 'VK_STRUCTURE_TYPE_DEVICE_BUFFER_MEMORY_REQUIREMENTS';
    VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO';
    VK_STRUCTURE_TYPE_DEVICE_GROUP_BIND_SPARSE_INFO: Result := 'VK_STRUCTURE_TYPE_DEVICE_GROUP_BIND_SPARSE_INFO';
    VK_STRUCTURE_TYPE_DEVICE_GROUP_COMMAND_BUFFER_BEGIN_INFO: Result := 'VK_STRUCTURE_TYPE_DEVICE_GROUP_COMMAND_BUFFER_BEGIN_INFO';
    VK_STRUCTURE_TYPE_DEVICE_GROUP_DEVICE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_DEVICE_GROUP_DEVICE_CREATE_INFO';
    VK_STRUCTURE_TYPE_DEVICE_GROUP_RENDER_PASS_BEGIN_INFO: Result := 'VK_STRUCTURE_TYPE_DEVICE_GROUP_RENDER_PASS_BEGIN_INFO';
    VK_STRUCTURE_TYPE_DEVICE_GROUP_SUBMIT_INFO: Result := 'VK_STRUCTURE_TYPE_DEVICE_GROUP_SUBMIT_INFO';
    VK_STRUCTURE_TYPE_DEVICE_IMAGE_MEMORY_REQUIREMENTS: Result := 'VK_STRUCTURE_TYPE_DEVICE_IMAGE_MEMORY_REQUIREMENTS';
    VK_STRUCTURE_TYPE_DEVICE_IMAGE_SUBRESOURCE_INFO: Result := 'VK_STRUCTURE_TYPE_DEVICE_IMAGE_SUBRESOURCE_INFO';
    VK_STRUCTURE_TYPE_DEVICE_MEMORY_OPAQUE_CAPTURE_ADDRESS_INFO: Result := 'VK_STRUCTURE_TYPE_DEVICE_MEMORY_OPAQUE_CAPTURE_ADDRESS_INFO';
    VK_STRUCTURE_TYPE_DEVICE_PRIVATE_DATA_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_DEVICE_PRIVATE_DATA_CREATE_INFO';
    VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO';
    VK_STRUCTURE_TYPE_DEVICE_QUEUE_GLOBAL_PRIORITY_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_DEVICE_QUEUE_GLOBAL_PRIORITY_CREATE_INFO';
    VK_STRUCTURE_TYPE_DEVICE_QUEUE_INFO_2: Result := 'VK_STRUCTURE_TYPE_DEVICE_QUEUE_INFO_2';
    VK_STRUCTURE_TYPE_DISPLAY_MODE_STEREO_PROPERTIES_NV: Result := 'VK_STRUCTURE_TYPE_DISPLAY_MODE_STEREO_PROPERTIES_NV';
    VK_STRUCTURE_TYPE_DISPLAY_SURFACE_STEREO_CREATE_INFO_NV: Result := 'VK_STRUCTURE_TYPE_DISPLAY_SURFACE_STEREO_CREATE_INFO_NV';
    VK_STRUCTURE_TYPE_EVENT_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_EVENT_CREATE_INFO';
    VK_STRUCTURE_TYPE_EXPORT_FENCE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_EXPORT_FENCE_CREATE_INFO';
    VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO: Result := 'VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO';
    VK_STRUCTURE_TYPE_EXPORT_SEMAPHORE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_EXPORT_SEMAPHORE_CREATE_INFO';
    VK_STRUCTURE_TYPE_EXTERNAL_BUFFER_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_EXTERNAL_BUFFER_PROPERTIES';
    VK_STRUCTURE_TYPE_EXTERNAL_COMPUTE_QUEUE_CREATE_INFO_NV: Result := 'VK_STRUCTURE_TYPE_EXTERNAL_COMPUTE_QUEUE_CREATE_INFO_NV';
    VK_STRUCTURE_TYPE_EXTERNAL_COMPUTE_QUEUE_DATA_PARAMS_NV: Result := 'VK_STRUCTURE_TYPE_EXTERNAL_COMPUTE_QUEUE_DATA_PARAMS_NV';
    VK_STRUCTURE_TYPE_EXTERNAL_COMPUTE_QUEUE_DEVICE_CREATE_INFO_NV: Result := 'VK_STRUCTURE_TYPE_EXTERNAL_COMPUTE_QUEUE_DEVICE_CREATE_INFO_NV';
    VK_STRUCTURE_TYPE_EXTERNAL_FENCE_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_EXTERNAL_FENCE_PROPERTIES';
    VK_STRUCTURE_TYPE_EXTERNAL_FORMAT_QNX: Result := 'VK_STRUCTURE_TYPE_EXTERNAL_FORMAT_QNX';
    VK_STRUCTURE_TYPE_EXTERNAL_IMAGE_FORMAT_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_EXTERNAL_IMAGE_FORMAT_PROPERTIES';
    VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO';
    VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO';
    VK_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_PROPERTIES';
    VK_STRUCTURE_TYPE_FENCE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_FENCE_CREATE_INFO';
    VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_2: Result := 'VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_2';
    VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_3: Result := 'VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_3';
    VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENT_IMAGE_INFO: Result := 'VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENT_IMAGE_INFO';
    VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENTS_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENTS_CREATE_INFO';
    VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO';
    VK_STRUCTURE_TYPE_GENERATED_COMMANDS_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_GENERATED_COMMANDS_INFO_EXT';
    VK_STRUCTURE_TYPE_GENERATED_COMMANDS_MEMORY_REQUIREMENTS_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_GENERATED_COMMANDS_MEMORY_REQUIREMENTS_INFO_EXT';
    VK_STRUCTURE_TYPE_GENERATED_COMMANDS_PIPELINE_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_GENERATED_COMMANDS_PIPELINE_INFO_EXT';
    VK_STRUCTURE_TYPE_GENERATED_COMMANDS_SHADER_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_GENERATED_COMMANDS_SHADER_INFO_EXT';
    VK_STRUCTURE_TYPE_GET_LATENCY_MARKER_INFO_NV: Result := 'VK_STRUCTURE_TYPE_GET_LATENCY_MARKER_INFO_NV';
    VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO';
    VK_STRUCTURE_TYPE_HDR_VIVID_DYNAMIC_METADATA_HUAWEI: Result := 'VK_STRUCTURE_TYPE_HDR_VIVID_DYNAMIC_METADATA_HUAWEI';
    VK_STRUCTURE_TYPE_HOST_IMAGE_COPY_DEVICE_PERFORMANCE_QUERY: Result := 'VK_STRUCTURE_TYPE_HOST_IMAGE_COPY_DEVICE_PERFORMANCE_QUERY';
    VK_STRUCTURE_TYPE_HOST_IMAGE_LAYOUT_TRANSITION_INFO: Result := 'VK_STRUCTURE_TYPE_HOST_IMAGE_LAYOUT_TRANSITION_INFO';
    VK_STRUCTURE_TYPE_IMAGE_ALIGNMENT_CONTROL_CREATE_INFO_MESA: Result := 'VK_STRUCTURE_TYPE_IMAGE_ALIGNMENT_CONTROL_CREATE_INFO_MESA';
    VK_STRUCTURE_TYPE_IMAGE_BLIT_2: Result := 'VK_STRUCTURE_TYPE_IMAGE_BLIT_2';
    VK_STRUCTURE_TYPE_IMAGE_COPY_2: Result := 'VK_STRUCTURE_TYPE_IMAGE_COPY_2';
    VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO';
    VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO';
    VK_STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2: Result := 'VK_STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2';
    VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER: Result := 'VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER';
    VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2: Result := 'VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2';
    VK_STRUCTURE_TYPE_IMAGE_MEMORY_REQUIREMENTS_INFO_2: Result := 'VK_STRUCTURE_TYPE_IMAGE_MEMORY_REQUIREMENTS_INFO_2';
    VK_STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO: Result := 'VK_STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO';
    VK_STRUCTURE_TYPE_IMAGE_RESOLVE_2: Result := 'VK_STRUCTURE_TYPE_IMAGE_RESOLVE_2';
    VK_STRUCTURE_TYPE_IMAGE_SPARSE_MEMORY_REQUIREMENTS_INFO_2: Result := 'VK_STRUCTURE_TYPE_IMAGE_SPARSE_MEMORY_REQUIREMENTS_INFO_2';
    VK_STRUCTURE_TYPE_IMAGE_STENCIL_USAGE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_IMAGE_STENCIL_USAGE_CREATE_INFO';
    VK_STRUCTURE_TYPE_IMAGE_SUBRESOURCE_2: Result := 'VK_STRUCTURE_TYPE_IMAGE_SUBRESOURCE_2';
    VK_STRUCTURE_TYPE_IMAGE_TO_MEMORY_COPY: Result := 'VK_STRUCTURE_TYPE_IMAGE_TO_MEMORY_COPY';
    VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO';
    VK_STRUCTURE_TYPE_IMAGE_VIEW_USAGE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_IMAGE_VIEW_USAGE_CREATE_INFO';
    VK_STRUCTURE_TYPE_IMPORT_MEMORY_METAL_HANDLE_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_IMPORT_MEMORY_METAL_HANDLE_INFO_EXT';
    VK_STRUCTURE_TYPE_IMPORT_SCREEN_BUFFER_INFO_QNX: Result := 'VK_STRUCTURE_TYPE_IMPORT_SCREEN_BUFFER_INFO_QNX';
    VK_STRUCTURE_TYPE_INDIRECT_COMMANDS_LAYOUT_CREATE_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_INDIRECT_COMMANDS_LAYOUT_CREATE_INFO_EXT';
    VK_STRUCTURE_TYPE_INDIRECT_COMMANDS_LAYOUT_TOKEN_EXT: Result := 'VK_STRUCTURE_TYPE_INDIRECT_COMMANDS_LAYOUT_TOKEN_EXT';
    VK_STRUCTURE_TYPE_INDIRECT_EXECUTION_SET_CREATE_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_INDIRECT_EXECUTION_SET_CREATE_INFO_EXT';
    VK_STRUCTURE_TYPE_INDIRECT_EXECUTION_SET_PIPELINE_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_INDIRECT_EXECUTION_SET_PIPELINE_INFO_EXT';
    VK_STRUCTURE_TYPE_INDIRECT_EXECUTION_SET_SHADER_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_INDIRECT_EXECUTION_SET_SHADER_INFO_EXT';
    VK_STRUCTURE_TYPE_INDIRECT_EXECUTION_SET_SHADER_LAYOUT_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_INDIRECT_EXECUTION_SET_SHADER_LAYOUT_INFO_EXT';
    VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO';
    VK_STRUCTURE_TYPE_LATENCY_SLEEP_INFO_NV: Result := 'VK_STRUCTURE_TYPE_LATENCY_SLEEP_INFO_NV';
    VK_STRUCTURE_TYPE_LATENCY_SLEEP_MODE_INFO_NV: Result := 'VK_STRUCTURE_TYPE_LATENCY_SLEEP_MODE_INFO_NV';
    VK_STRUCTURE_TYPE_LATENCY_SUBMISSION_PRESENT_ID_NV: Result := 'VK_STRUCTURE_TYPE_LATENCY_SUBMISSION_PRESENT_ID_NV';
    VK_STRUCTURE_TYPE_LATENCY_SURFACE_CAPABILITIES_NV: Result := 'VK_STRUCTURE_TYPE_LATENCY_SURFACE_CAPABILITIES_NV';
    VK_STRUCTURE_TYPE_LATENCY_TIMINGS_FRAME_REPORT_NV: Result := 'VK_STRUCTURE_TYPE_LATENCY_TIMINGS_FRAME_REPORT_NV';
    VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO';
    VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO';
    VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE: Result := 'VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE';
    VK_STRUCTURE_TYPE_MAX_ENUM: Result := 'VK_STRUCTURE_TYPE_MAX_ENUM';
    VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO: Result := 'VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO';
    VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO: Result := 'VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO';
    VK_STRUCTURE_TYPE_MEMORY_BARRIER: Result := 'VK_STRUCTURE_TYPE_MEMORY_BARRIER';
    VK_STRUCTURE_TYPE_MEMORY_BARRIER_2: Result := 'VK_STRUCTURE_TYPE_MEMORY_BARRIER_2';
    VK_STRUCTURE_TYPE_MEMORY_BARRIER_ACCESS_FLAGS_3_KHR: Result := 'VK_STRUCTURE_TYPE_MEMORY_BARRIER_ACCESS_FLAGS_3_KHR';
    VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO: Result := 'VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO';
    VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS: Result := 'VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS';
    VK_STRUCTURE_TYPE_MEMORY_GET_METAL_HANDLE_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_MEMORY_GET_METAL_HANDLE_INFO_EXT';
    VK_STRUCTURE_TYPE_MEMORY_MAP_INFO: Result := 'VK_STRUCTURE_TYPE_MEMORY_MAP_INFO';
    VK_STRUCTURE_TYPE_MEMORY_METAL_HANDLE_PROPERTIES_EXT: Result := 'VK_STRUCTURE_TYPE_MEMORY_METAL_HANDLE_PROPERTIES_EXT';
    VK_STRUCTURE_TYPE_MEMORY_OPAQUE_CAPTURE_ADDRESS_ALLOCATE_INFO: Result := 'VK_STRUCTURE_TYPE_MEMORY_OPAQUE_CAPTURE_ADDRESS_ALLOCATE_INFO';
    VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2: Result := 'VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2';
    VK_STRUCTURE_TYPE_MEMORY_TO_IMAGE_COPY: Result := 'VK_STRUCTURE_TYPE_MEMORY_TO_IMAGE_COPY';
    VK_STRUCTURE_TYPE_MEMORY_UNMAP_INFO: Result := 'VK_STRUCTURE_TYPE_MEMORY_UNMAP_INFO';
    VK_STRUCTURE_TYPE_MULTIVIEW_PER_VIEW_RENDER_AREAS_RENDER_PASS_BEGIN_INFO_QCOM: Result := 'VK_STRUCTURE_TYPE_MULTIVIEW_PER_VIEW_RENDER_AREAS_RENDER_PASS_BEGIN_INFO_QCOM';
    VK_STRUCTURE_TYPE_OUT_OF_BAND_QUEUE_TYPE_INFO_NV: Result := 'VK_STRUCTURE_TYPE_OUT_OF_BAND_QUEUE_TYPE_INFO_NV';
    VK_STRUCTURE_TYPE_PERFORMANCE_COUNTER_ARM: Result := 'VK_STRUCTURE_TYPE_PERFORMANCE_COUNTER_ARM';
    VK_STRUCTURE_TYPE_PERFORMANCE_COUNTER_DESCRIPTION_ARM: Result := 'VK_STRUCTURE_TYPE_PERFORMANCE_COUNTER_DESCRIPTION_ARM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_8BIT_STORAGE_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_8BIT_STORAGE_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ATTACHMENT_FEEDBACK_LOOP_DYNAMIC_STATE_FEATURES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ATTACHMENT_FEEDBACK_LOOP_DYNAMIC_STATE_FEATURES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BORDER_COLOR_SWIZZLE_FEATURES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BORDER_COLOR_SWIZZLE_FEATURES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CLUSTER_CULLING_SHADER_FEATURES_HUAWEI: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CLUSTER_CULLING_SHADER_FEATURES_HUAWEI';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CLUSTER_CULLING_SHADER_PROPERTIES_HUAWEI: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CLUSTER_CULLING_SHADER_PROPERTIES_HUAWEI';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CLUSTER_CULLING_SHADER_VRS_FEATURES_HUAWEI: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CLUSTER_CULLING_SHADER_VRS_FEATURES_HUAWEI';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COMMAND_BUFFER_INHERITANCE_FEATURES_NV: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COMMAND_BUFFER_INHERITANCE_FEATURES_NV';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COMPUTE_OCCUPANCY_PRIORITY_FEATURES_NV: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COMPUTE_OCCUPANCY_PRIORITY_FEATURES_NV';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COMPUTE_SHADER_DERIVATIVES_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COMPUTE_SHADER_DERIVATIVES_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COMPUTE_SHADER_DERIVATIVES_PROPERTIES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COMPUTE_SHADER_DERIVATIVES_PROPERTIES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_2_FEATURES_NV: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_2_FEATURES_NV';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_2_PROPERTIES_NV: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_2_PROPERTIES_NV';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_PROPERTIES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_PROPERTIES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COPY_MEMORY_INDIRECT_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COPY_MEMORY_INDIRECT_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COPY_MEMORY_INDIRECT_PROPERTIES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COPY_MEMORY_INDIRECT_PROPERTIES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CUBIC_CLAMP_FEATURES_QCOM: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CUBIC_CLAMP_FEATURES_QCOM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CUBIC_WEIGHTS_FEATURES_QCOM: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CUBIC_WEIGHTS_FEATURES_QCOM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CUSTOM_RESOLVE_FEATURES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CUSTOM_RESOLVE_FEATURES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DATA_GRAPH_FEATURES_ARM: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DATA_GRAPH_FEATURES_ARM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DATA_GRAPH_MODEL_FEATURES_QCOM: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DATA_GRAPH_MODEL_FEATURES_QCOM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_CLAMP_CONTROL_FEATURES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_CLAMP_CONTROL_FEATURES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_CLAMP_ZERO_ONE_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_CLAMP_ZERO_ONE_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_STENCIL_RESOLVE_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_STENCIL_RESOLVE_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_POOL_OVERALLOCATION_FEATURES_NV: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_POOL_OVERALLOCATION_FEATURES_NV';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEVICE_GENERATED_COMMANDS_FEATURES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEVICE_GENERATED_COMMANDS_FEATURES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEVICE_GENERATED_COMMANDS_PROPERTIES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEVICE_GENERATED_COMMANDS_PROPERTIES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DISPLACEMENT_MICROMAP_FEATURES_NV: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DISPLACEMENT_MICROMAP_FEATURES_NV';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DISPLACEMENT_MICROMAP_PROPERTIES_NV: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DISPLACEMENT_MICROMAP_PROPERTIES_NV';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DRIVER_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DRIVER_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DYNAMIC_RENDERING_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DYNAMIC_RENDERING_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DYNAMIC_RENDERING_UNUSED_ATTACHMENTS_FEATURES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DYNAMIC_RENDERING_UNUSED_ATTACHMENTS_FEATURES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_COMPUTE_QUEUE_PROPERTIES_NV: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_COMPUTE_QUEUE_PROPERTIES_NV';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_FENCE_INFO: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_FENCE_INFO';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_MEMORY_SCREEN_BUFFER_FEATURES_QNX: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_MEMORY_SCREEN_BUFFER_FEATURES_QNX';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_SEMAPHORE_INFO: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_SEMAPHORE_INFO';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FLOAT_CONTROLS_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FLOAT_CONTROLS_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FORMAT_PACK_FEATURES_ARM: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FORMAT_PACK_FEATURES_ARM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_LAYERED_FEATURES_VALVE: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_LAYERED_FEATURES_VALVE';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_LAYERED_PROPERTIES_VALVE: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_LAYERED_PROPERTIES_VALVE';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_OFFSET_FEATURES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_OFFSET_FEATURES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_OFFSET_PROPERTIES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_OFFSET_PROPERTIES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GLOBAL_PRIORITY_QUERY_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GLOBAL_PRIORITY_QUERY_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_HDR_VIVID_FEATURES_HUAWEI: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_HDR_VIVID_FEATURES_HUAWEI';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_HOST_IMAGE_COPY_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_HOST_IMAGE_COPY_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_HOST_IMAGE_COPY_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_HOST_IMAGE_COPY_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_HOST_QUERY_RESET_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_HOST_QUERY_RESET_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_ALIGNMENT_CONTROL_FEATURES_MESA: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_ALIGNMENT_CONTROL_FEATURES_MESA';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_ALIGNMENT_CONTROL_PROPERTIES_MESA: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_ALIGNMENT_CONTROL_PROPERTIES_MESA';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_PROCESSING_2_FEATURES_QCOM: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_PROCESSING_2_FEATURES_QCOM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_PROCESSING_2_PROPERTIES_QCOM: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_PROCESSING_2_PROPERTIES_QCOM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_ROBUSTNESS_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_ROBUSTNESS_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGELESS_FRAMEBUFFER_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGELESS_FRAMEBUFFER_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INDEX_TYPE_UINT8_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INDEX_TYPE_UINT8_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_LAYERED_DRIVER_PROPERTIES_MSFT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_LAYERED_DRIVER_PROPERTIES_MSFT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_10_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_10_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_10_PROPERTIES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_10_PROPERTIES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_3_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_3_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_4_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_4_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_4_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_4_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_5_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_5_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_5_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_5_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_6_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_6_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_6_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_6_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_7_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_7_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_7_PROPERTIES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_7_PROPERTIES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_8_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_8_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_9_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_9_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_9_PROPERTIES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_9_PROPERTIES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_DECOMPRESSION_FEATURES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_DECOMPRESSION_FEATURES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_DECOMPRESSION_PROPERTIES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_DECOMPRESSION_PROPERTIES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PROPERTIES_2: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PROPERTIES_2';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PER_VIEW_RENDER_AREAS_FEATURES_QCOM: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PER_VIEW_RENDER_AREAS_FEATURES_QCOM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PAGEABLE_DEVICE_LOCAL_MEMORY_FEATURES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PAGEABLE_DEVICE_LOCAL_MEMORY_FEATURES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PER_STAGE_DESCRIPTOR_SET_FEATURES_NV: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PER_STAGE_DESCRIPTOR_SET_FEATURES_NV';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PERFORMANCE_COUNTERS_BY_REGION_FEATURES_ARM: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PERFORMANCE_COUNTERS_BY_REGION_FEATURES_ARM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PERFORMANCE_COUNTERS_BY_REGION_PROPERTIES_ARM: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PERFORMANCE_COUNTERS_BY_REGION_PROPERTIES_ARM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_CACHE_INCREMENTAL_MODE_FEATURES_SEC: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_CACHE_INCREMENTAL_MODE_FEATURES_SEC';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_CREATION_CACHE_CONTROL_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_CREATION_CACHE_CONTROL_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_LIBRARY_GROUP_HANDLES_FEATURES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_LIBRARY_GROUP_HANDLES_FEATURES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_OPACITY_MICROMAP_FEATURES_ARM: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_OPACITY_MICROMAP_FEATURES_ARM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_POINT_CLIPPING_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_POINT_CLIPPING_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PRESENT_METERING_FEATURES_NV: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PRESENT_METERING_FEATURES_NV';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PRESENT_MODE_FIFO_LATEST_READY_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PRESENT_MODE_FIFO_LATEST_READY_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PRIVATE_DATA_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PRIVATE_DATA_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_QUEUE_FAMILY_DATA_GRAPH_PROCESSING_ENGINE_INFO_ARM: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_QUEUE_FAMILY_DATA_GRAPH_PROCESSING_ENGINE_INFO_ARM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAW_ACCESS_CHAINS_FEATURES_NV: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAW_ACCESS_CHAINS_FEATURES_NV';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_INVOCATION_REORDER_FEATURES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_INVOCATION_REORDER_FEATURES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_INVOCATION_REORDER_PROPERTIES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_INVOCATION_REORDER_PROPERTIES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ROBUSTNESS_2_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ROBUSTNESS_2_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ROBUSTNESS_2_PROPERTIES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ROBUSTNESS_2_PROPERTIES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_FILTER_MINMAX_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_FILTER_MINMAX_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SCALAR_BLOCK_LAYOUT_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SCALAR_BLOCK_LAYOUT_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SEPARATE_DEPTH_STENCIL_LAYOUTS_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SEPARATE_DEPTH_STENCIL_LAYOUTS_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_64_BIT_INDEXING_FEATURES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_64_BIT_INDEXING_FEATURES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ATOMIC_INT64_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ATOMIC_INT64_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_BUILTINS_FEATURES_ARM: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_BUILTINS_FEATURES_ARM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_BUILTINS_PROPERTIES_ARM: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_BUILTINS_PROPERTIES_ARM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DEMOTE_TO_HELPER_INVOCATION_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DEMOTE_TO_HELPER_INVOCATION_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DRAW_PARAMETERS_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DRAW_PARAMETERS_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_FLOAT16_INT8_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_FLOAT16_INT8_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_FMA_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_FMA_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_INTEGER_DOT_PRODUCT_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_INTEGER_DOT_PRODUCT_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_INTEGER_DOT_PRODUCT_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_INTEGER_DOT_PRODUCT_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_LONG_VECTOR_FEATURES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_LONG_VECTOR_FEATURES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_LONG_VECTOR_PROPERTIES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_LONG_VECTOR_PROPERTIES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_RELAXED_EXTENDED_INSTRUCTION_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_RELAXED_EXTENDED_INSTRUCTION_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_SUBGROUP_EXTENDED_TYPES_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_SUBGROUP_EXTENDED_TYPES_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_TERMINATE_INVOCATION_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_TERMINATE_INVOCATION_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_UNIFORM_BUFFER_UNSIZED_ARRAY_FEATURES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_UNIFORM_BUFFER_UNSIZED_ARRAY_FEATURES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SPARSE_IMAGE_FORMAT_INFO_2: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SPARSE_IMAGE_FORMAT_INFO_2';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_SIZE_CONTROL_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_SIZE_CONTROL_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_SIZE_CONTROL_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_SIZE_CONTROL_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SYNCHRONIZATION_2_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SYNCHRONIZATION_2_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TEXEL_BUFFER_ALIGNMENT_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TEXEL_BUFFER_ALIGNMENT_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TEXTURE_COMPRESSION_ASTC_HDR_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TEXTURE_COMPRESSION_ASTC_HDR_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TILE_MEMORY_HEAP_FEATURES_QCOM: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TILE_MEMORY_HEAP_FEATURES_QCOM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TILE_MEMORY_HEAP_PROPERTIES_QCOM: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TILE_MEMORY_HEAP_PROPERTIES_QCOM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TIMELINE_SEMAPHORE_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TIMELINE_SEMAPHORE_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TIMELINE_SEMAPHORE_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TIMELINE_SEMAPHORE_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TOOL_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TOOL_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_UNIFIED_IMAGE_LAYOUTS_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_UNIFIED_IMAGE_LAYOUTS_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_UNIFORM_BUFFER_STANDARD_LAYOUT_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_UNIFORM_BUFFER_STANDARD_LAYOUT_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VARIABLE_POINTERS_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VARIABLE_POINTERS_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_ROBUSTNESS_FEATURES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_ROBUSTNESS_FEATURES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VIDEO_DECODE_VP9_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VIDEO_DECODE_VP9_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VIDEO_ENCODE_AV1_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VIDEO_ENCODE_AV1_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VIDEO_ENCODE_INTRA_REFRESH_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VIDEO_ENCODE_INTRA_REFRESH_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VIDEO_ENCODE_QUANTIZATION_MAP_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VIDEO_ENCODE_QUANTIZATION_MAP_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VIDEO_MAINTENANCE_1_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VIDEO_MAINTENANCE_1_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VIDEO_MAINTENANCE_2_FEATURES_KHR: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VIDEO_MAINTENANCE_2_FEATURES_KHR';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_4_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_4_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_4_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_4_PROPERTIES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_MEMORY_MODEL_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_MEMORY_MODEL_FEATURES';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_YCBCR_DEGAMMA_FEATURES_QCOM: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_YCBCR_DEGAMMA_FEATURES_QCOM';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ZERO_INITIALIZE_DEVICE_MEMORY_FEATURES_EXT: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ZERO_INITIALIZE_DEVICE_MEMORY_FEATURES_EXT';
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ZERO_INITIALIZE_WORKGROUP_MEMORY_FEATURES: Result := 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ZERO_INITIALIZE_WORKGROUP_MEMORY_FEATURES';
    VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO';
    VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO';
    VK_STRUCTURE_TYPE_PIPELINE_CREATION_FEEDBACK_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_PIPELINE_CREATION_FEEDBACK_CREATE_INFO';
    VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO';
    VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO';
    VK_STRUCTURE_TYPE_PIPELINE_FRAGMENT_DENSITY_MAP_LAYERED_CREATE_INFO_VALVE: Result := 'VK_STRUCTURE_TYPE_PIPELINE_FRAGMENT_DENSITY_MAP_LAYERED_CREATE_INFO_VALVE';
    VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO';
    VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO';
    VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO';
    VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO';
    VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO';
    VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO';
    VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_REQUIRED_SUBGROUP_SIZE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_REQUIRED_SUBGROUP_SIZE_CREATE_INFO';
    VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_DOMAIN_ORIGIN_STATE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_DOMAIN_ORIGIN_STATE_CREATE_INFO';
    VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO';
    VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO';
    VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_DEPTH_CLAMP_CONTROL_CREATE_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_DEPTH_CLAMP_CONTROL_CREATE_INFO_EXT';
    VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO';
    VK_STRUCTURE_TYPE_PRIVATE_DATA_SLOT_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_PRIVATE_DATA_SLOT_CREATE_INFO';
    VK_STRUCTURE_TYPE_PROTECTED_SUBMIT_INFO: Result := 'VK_STRUCTURE_TYPE_PROTECTED_SUBMIT_INFO';
    VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO';
    VK_STRUCTURE_TYPE_QUEUE_FAMILY_DATA_GRAPH_PROCESSING_ENGINE_PROPERTIES_ARM: Result := 'VK_STRUCTURE_TYPE_QUEUE_FAMILY_DATA_GRAPH_PROCESSING_ENGINE_PROPERTIES_ARM';
    VK_STRUCTURE_TYPE_QUEUE_FAMILY_DATA_GRAPH_PROPERTIES_ARM: Result := 'VK_STRUCTURE_TYPE_QUEUE_FAMILY_DATA_GRAPH_PROPERTIES_ARM';
    VK_STRUCTURE_TYPE_QUEUE_FAMILY_GLOBAL_PRIORITY_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_QUEUE_FAMILY_GLOBAL_PRIORITY_PROPERTIES';
    VK_STRUCTURE_TYPE_QUEUE_FAMILY_OWNERSHIP_TRANSFER_PROPERTIES_KHR: Result := 'VK_STRUCTURE_TYPE_QUEUE_FAMILY_OWNERSHIP_TRANSFER_PROPERTIES_KHR';
    VK_STRUCTURE_TYPE_QUEUE_FAMILY_PROPERTIES_2: Result := 'VK_STRUCTURE_TYPE_QUEUE_FAMILY_PROPERTIES_2';
    VK_STRUCTURE_TYPE_RENDER_PASS_ATTACHMENT_BEGIN_INFO: Result := 'VK_STRUCTURE_TYPE_RENDER_PASS_ATTACHMENT_BEGIN_INFO';
    VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO: Result := 'VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO';
    VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO';
    VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO_2: Result := 'VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO_2';
    VK_STRUCTURE_TYPE_RENDER_PASS_FRAGMENT_DENSITY_MAP_OFFSET_END_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_RENDER_PASS_FRAGMENT_DENSITY_MAP_OFFSET_END_INFO_EXT';
    VK_STRUCTURE_TYPE_RENDER_PASS_INPUT_ATTACHMENT_ASPECT_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_RENDER_PASS_INPUT_ATTACHMENT_ASPECT_CREATE_INFO';
    VK_STRUCTURE_TYPE_RENDER_PASS_MULTIVIEW_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_RENDER_PASS_MULTIVIEW_CREATE_INFO';
    VK_STRUCTURE_TYPE_RENDER_PASS_PERFORMANCE_COUNTERS_BY_REGION_BEGIN_INFO_ARM: Result := 'VK_STRUCTURE_TYPE_RENDER_PASS_PERFORMANCE_COUNTERS_BY_REGION_BEGIN_INFO_ARM';
    VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_FLAGS_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_FLAGS_INFO_KHR';
    VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO: Result := 'VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO';
    VK_STRUCTURE_TYPE_RENDERING_END_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_RENDERING_END_INFO_KHR';
    VK_STRUCTURE_TYPE_RENDERING_INFO: Result := 'VK_STRUCTURE_TYPE_RENDERING_INFO';
    VK_STRUCTURE_TYPE_RESOLVE_IMAGE_INFO_2: Result := 'VK_STRUCTURE_TYPE_RESOLVE_IMAGE_INFO_2';
    VK_STRUCTURE_TYPE_RESOLVE_IMAGE_MODE_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_RESOLVE_IMAGE_MODE_INFO_KHR';
    VK_STRUCTURE_TYPE_SAMPLER_BLOCK_MATCH_WINDOW_CREATE_INFO_QCOM: Result := 'VK_STRUCTURE_TYPE_SAMPLER_BLOCK_MATCH_WINDOW_CREATE_INFO_QCOM';
    VK_STRUCTURE_TYPE_SAMPLER_BORDER_COLOR_COMPONENT_MAPPING_CREATE_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_SAMPLER_BORDER_COLOR_COMPONENT_MAPPING_CREATE_INFO_EXT';
    VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO';
    VK_STRUCTURE_TYPE_SAMPLER_CUBIC_WEIGHTS_CREATE_INFO_QCOM: Result := 'VK_STRUCTURE_TYPE_SAMPLER_CUBIC_WEIGHTS_CREATE_INFO_QCOM';
    VK_STRUCTURE_TYPE_SAMPLER_REDUCTION_MODE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_SAMPLER_REDUCTION_MODE_CREATE_INFO';
    VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO';
    VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES: Result := 'VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES';
    VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO: Result := 'VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO';
    VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_YCBCR_DEGAMMA_CREATE_INFO_QCOM: Result := 'VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_YCBCR_DEGAMMA_CREATE_INFO_QCOM';
    VK_STRUCTURE_TYPE_SCREEN_BUFFER_FORMAT_PROPERTIES_QNX: Result := 'VK_STRUCTURE_TYPE_SCREEN_BUFFER_FORMAT_PROPERTIES_QNX';
    VK_STRUCTURE_TYPE_SCREEN_BUFFER_PROPERTIES_QNX: Result := 'VK_STRUCTURE_TYPE_SCREEN_BUFFER_PROPERTIES_QNX';
    VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO';
    VK_STRUCTURE_TYPE_SEMAPHORE_SIGNAL_INFO: Result := 'VK_STRUCTURE_TYPE_SEMAPHORE_SIGNAL_INFO';
    VK_STRUCTURE_TYPE_SEMAPHORE_SUBMIT_INFO: Result := 'VK_STRUCTURE_TYPE_SEMAPHORE_SUBMIT_INFO';
    VK_STRUCTURE_TYPE_SEMAPHORE_TYPE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_SEMAPHORE_TYPE_CREATE_INFO';
    VK_STRUCTURE_TYPE_SEMAPHORE_WAIT_INFO: Result := 'VK_STRUCTURE_TYPE_SEMAPHORE_WAIT_INFO';
    VK_STRUCTURE_TYPE_SET_DESCRIPTOR_BUFFER_OFFSETS_INFO_EXT: Result := 'VK_STRUCTURE_TYPE_SET_DESCRIPTOR_BUFFER_OFFSETS_INFO_EXT';
    VK_STRUCTURE_TYPE_SET_LATENCY_MARKER_INFO_NV: Result := 'VK_STRUCTURE_TYPE_SET_LATENCY_MARKER_INFO_NV';
    VK_STRUCTURE_TYPE_SET_PRESENT_CONFIG_NV: Result := 'VK_STRUCTURE_TYPE_SET_PRESENT_CONFIG_NV';
    VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO: Result := 'VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO';
    VK_STRUCTURE_TYPE_SPARSE_IMAGE_FORMAT_PROPERTIES_2: Result := 'VK_STRUCTURE_TYPE_SPARSE_IMAGE_FORMAT_PROPERTIES_2';
    VK_STRUCTURE_TYPE_SPARSE_IMAGE_MEMORY_REQUIREMENTS_2: Result := 'VK_STRUCTURE_TYPE_SPARSE_IMAGE_MEMORY_REQUIREMENTS_2';
    VK_STRUCTURE_TYPE_SUBMIT_INFO: Result := 'VK_STRUCTURE_TYPE_SUBMIT_INFO';
    VK_STRUCTURE_TYPE_SUBMIT_INFO_2: Result := 'VK_STRUCTURE_TYPE_SUBMIT_INFO_2';
    VK_STRUCTURE_TYPE_SUBPASS_BEGIN_INFO: Result := 'VK_STRUCTURE_TYPE_SUBPASS_BEGIN_INFO';
    VK_STRUCTURE_TYPE_SUBPASS_DEPENDENCY_2: Result := 'VK_STRUCTURE_TYPE_SUBPASS_DEPENDENCY_2';
    VK_STRUCTURE_TYPE_SUBPASS_DESCRIPTION_2: Result := 'VK_STRUCTURE_TYPE_SUBPASS_DESCRIPTION_2';
    VK_STRUCTURE_TYPE_SUBPASS_DESCRIPTION_DEPTH_STENCIL_RESOLVE: Result := 'VK_STRUCTURE_TYPE_SUBPASS_DESCRIPTION_DEPTH_STENCIL_RESOLVE';
    VK_STRUCTURE_TYPE_SUBPASS_END_INFO: Result := 'VK_STRUCTURE_TYPE_SUBPASS_END_INFO';
    VK_STRUCTURE_TYPE_SUBRESOURCE_HOST_MEMCPY_SIZE: Result := 'VK_STRUCTURE_TYPE_SUBRESOURCE_HOST_MEMCPY_SIZE';
    VK_STRUCTURE_TYPE_SUBRESOURCE_LAYOUT_2: Result := 'VK_STRUCTURE_TYPE_SUBRESOURCE_LAYOUT_2';
    VK_STRUCTURE_TYPE_SURFACE_CREATE_INFO_OHOS: Result := 'VK_STRUCTURE_TYPE_SURFACE_CREATE_INFO_OHOS';
    VK_STRUCTURE_TYPE_SWAPCHAIN_LATENCY_CREATE_INFO_NV: Result := 'VK_STRUCTURE_TYPE_SWAPCHAIN_LATENCY_CREATE_INFO_NV';
    VK_STRUCTURE_TYPE_TILE_MEMORY_BIND_INFO_QCOM: Result := 'VK_STRUCTURE_TYPE_TILE_MEMORY_BIND_INFO_QCOM';
    VK_STRUCTURE_TYPE_TILE_MEMORY_REQUIREMENTS_QCOM: Result := 'VK_STRUCTURE_TYPE_TILE_MEMORY_REQUIREMENTS_QCOM';
    VK_STRUCTURE_TYPE_TILE_MEMORY_SIZE_INFO_QCOM: Result := 'VK_STRUCTURE_TYPE_TILE_MEMORY_SIZE_INFO_QCOM';
    VK_STRUCTURE_TYPE_TIMELINE_SEMAPHORE_SUBMIT_INFO: Result := 'VK_STRUCTURE_TYPE_TIMELINE_SEMAPHORE_SUBMIT_INFO';
    VK_STRUCTURE_TYPE_VIDEO_DECODE_AV1_CAPABILITIES_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_DECODE_AV1_CAPABILITIES_KHR';
    VK_STRUCTURE_TYPE_VIDEO_DECODE_AV1_DPB_SLOT_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_DECODE_AV1_DPB_SLOT_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_DECODE_AV1_INLINE_SESSION_PARAMETERS_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_DECODE_AV1_INLINE_SESSION_PARAMETERS_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_DECODE_AV1_PICTURE_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_DECODE_AV1_PICTURE_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_DECODE_AV1_PROFILE_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_DECODE_AV1_PROFILE_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_DECODE_AV1_SESSION_PARAMETERS_CREATE_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_DECODE_AV1_SESSION_PARAMETERS_CREATE_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_DECODE_H264_INLINE_SESSION_PARAMETERS_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_DECODE_H264_INLINE_SESSION_PARAMETERS_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_DECODE_H265_INLINE_SESSION_PARAMETERS_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_DECODE_H265_INLINE_SESSION_PARAMETERS_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_DECODE_VP9_CAPABILITIES_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_DECODE_VP9_CAPABILITIES_KHR';
    VK_STRUCTURE_TYPE_VIDEO_DECODE_VP9_PICTURE_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_DECODE_VP9_PICTURE_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_DECODE_VP9_PROFILE_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_DECODE_VP9_PROFILE_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_CAPABILITIES_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_CAPABILITIES_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_DPB_SLOT_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_DPB_SLOT_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_GOP_REMAINING_FRAME_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_GOP_REMAINING_FRAME_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_PICTURE_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_PICTURE_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_PROFILE_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_PROFILE_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_QUALITY_LEVEL_PROPERTIES_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_QUALITY_LEVEL_PROPERTIES_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_QUANTIZATION_MAP_CAPABILITIES_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_QUANTIZATION_MAP_CAPABILITIES_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_RATE_CONTROL_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_RATE_CONTROL_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_RATE_CONTROL_LAYER_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_RATE_CONTROL_LAYER_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_SESSION_CREATE_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_SESSION_CREATE_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_SESSION_PARAMETERS_CREATE_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_AV1_SESSION_PARAMETERS_CREATE_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_H264_QUANTIZATION_MAP_CAPABILITIES_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_H264_QUANTIZATION_MAP_CAPABILITIES_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_H265_QUANTIZATION_MAP_CAPABILITIES_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_H265_QUANTIZATION_MAP_CAPABILITIES_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_INTRA_REFRESH_CAPABILITIES_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_INTRA_REFRESH_CAPABILITIES_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_INTRA_REFRESH_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_INTRA_REFRESH_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_QUANTIZATION_MAP_CAPABILITIES_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_QUANTIZATION_MAP_CAPABILITIES_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_QUANTIZATION_MAP_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_QUANTIZATION_MAP_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_QUANTIZATION_MAP_SESSION_PARAMETERS_CREATE_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_QUANTIZATION_MAP_SESSION_PARAMETERS_CREATE_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_ENCODE_SESSION_INTRA_REFRESH_CREATE_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_ENCODE_SESSION_INTRA_REFRESH_CREATE_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_FORMAT_AV1_QUANTIZATION_MAP_PROPERTIES_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_FORMAT_AV1_QUANTIZATION_MAP_PROPERTIES_KHR';
    VK_STRUCTURE_TYPE_VIDEO_FORMAT_H265_QUANTIZATION_MAP_PROPERTIES_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_FORMAT_H265_QUANTIZATION_MAP_PROPERTIES_KHR';
    VK_STRUCTURE_TYPE_VIDEO_FORMAT_QUANTIZATION_MAP_PROPERTIES_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_FORMAT_QUANTIZATION_MAP_PROPERTIES_KHR';
    VK_STRUCTURE_TYPE_VIDEO_INLINE_QUERY_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_INLINE_QUERY_INFO_KHR';
    VK_STRUCTURE_TYPE_VIDEO_REFERENCE_INTRA_REFRESH_INFO_KHR: Result := 'VK_STRUCTURE_TYPE_VIDEO_REFERENCE_INTRA_REFRESH_INFO_KHR';
    VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET: Result := 'VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET';
    VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET_INLINE_UNIFORM_BLOCK: Result := 'VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET_INLINE_UNIFORM_BLOCK';
    VK_STRUCTURE_TYPE_WRITE_INDIRECT_EXECUTION_SET_PIPELINE_EXT: Result := 'VK_STRUCTURE_TYPE_WRITE_INDIRECT_EXECUTION_SET_PIPELINE_EXT';
    VK_STRUCTURE_TYPE_WRITE_INDIRECT_EXECUTION_SET_SHADER_EXT: Result := 'VK_STRUCTURE_TYPE_WRITE_INDIRECT_EXECUTION_SET_SHADER_EXT';
    else
      Result := Format('Unknown VkStructureType (%d)', [Ord(sType)]);
  end;
end;

function PtrUIntToHex(p: Pointer): string;
begin
  Result := Format('0x%.16x', [PtrUInt(p)]);
end;

function PtrToHex(p: Pointer): string;
begin
  Result := Format('0x%.16x', [PtrInt(p)]);
end;

function PtrToHexClean(p: Pointer): string;
begin
  Result := Format('%.16x', [PtrInt(p)]);
end;

function PtrToHexShort(p: Pointer): string;
begin
  Result := Format('%.8x', [PtrInt(p)]);
end;

function PtrToHexEx(p: Pointer; Digits: integer = 16): string;
begin
  Result := Format('0x%.' + IntToStr(Digits) + 'x', [PtrInt(p)]);
end;

operator := (ptr: Pointer): QWord;
var
  abs: QWord absolute ptr;
begin
  Result := abs;
end;

operator := (num: QWord): Pointer;
var
  abs: Pointer absolute num;
begin
  Result := abs;
end;

operator <>(num: QWord; ptr: Pointer): boolean;
var
  abs: QWord absolute ptr;
begin
  Result := num <> abs;
end;

operator := (ai: VkApplicationInfo): string;
begin
  Result := ai.ToString;
end;

operator := (ici: VkInstanceCreateInfo): string;
begin
  Result := ici.ToString;
end;

operator := (sa: TStringArray): PPChar;
var
  i: integer;
begin
  GetMem(Result, Length(sa) * SizeOf(PChar));
  for i := Low(sa) to High(sa) do
    Result[i] := PChar(sa[i]);
end;

operator := (sa: TStringArray): string;
var
  i: integer;
begin
  Result := '';
  for i := Low(sa) to High(sa) do
  begin
    if Result <> '' then Result := Result + ', ';
    Result := Result + '"' + sa[i] + '"';
  end;
  Result := '[' + Result + ']';
end;

function IfThen(val: boolean; const iftrue: string; const iffalse: string): string; inline; overload;
begin
  if val then
    Result := iftrue
  else
    Result := iffalse;
end;

{ TVulkanTutorial }

constructor TVulkanTutorial.Create;
begin
  inherited Create;
  FInstanceExtensions := TStringList.Create(True);
  FDeviceExtensions := TStringList.Create(True);
  FDeviceFeatures := TStringList.Create(True);
  FEnableValidationLayers := True;
  FCaption := 'Vulkan Tutorial';
end;

destructor TVulkanTutorial.Destroy;
begin
  getLogger.Enter('TVulkanTutorial', 'Destroy');
  FreeAndNil(FDeviceFeatures);
  FreeAndNil(FDeviceExtensions);
  FreeAndNil(FInstanceExtensions);
  Cleanup;
  inherited Destroy;
  getLogger.Leave('TVulkanTutorial', 'Destroy');
end;

procedure TVulkanTutorial.run;
begin
  GetLogger.Enter('TVulkanTutorial', 'run');
  try
    InitWindow;
    InitVulkan;
    MainLoop;
  except
    on E: Exception do
    begin
      GetLogger.Error('Eccezione in run: %s', [E.Message]);
    end;
  end;
  GetLogger.Leave('TVulkanTutorial', 'run');
end;

function TVulkanTutorial.GetCaption: string;
begin
  Result := FCaption;
end;

procedure TVulkanTutorial.SetCaption(AValue: string);
begin
  if FCaption = AValue then Exit;
  FCaption := AValue;
end;

function TVulkanTutorial.getLogger: TLogger;
begin
  Result := TutorialLogger;
end;

function TVulkanTutorial.GetEnableValidationLayers: boolean;
begin
  Result := FEnableValidationLayers;
end;

procedure TVulkanTutorial.SetEnableValidationLayers(AValue: boolean);
begin
  FEnableValidationLayers := AValue;
end;

{ TStringArrayTypeHelper }

function TStringArrayTypeHelper.toPPChar: PPChar;
var
  i: integer;
begin
  GetMem(Result, Length(Self) * SizeOf(PChar));
  for i := 0 to High(Self) do
    Result[i] := PChar(Self[i]);
end;

function TStringArrayTypeHelper.Text: string;
var
  s: string;
begin
  Result := '';
  for s in Self do
    Result := Result + s + LineEnding;
end;

function TStringArrayTypeHelper.formattedString: string;
var
  i: integer;
begin
  Result := '';
  for i := Low(Self) to High(Self) do
  begin
    if Result <> '' then Result := Result + ', ';
    Result := Result + '"' + Self[i] + '"';
  end;
  Result := '[' + Result + ']';
end;

{ TPPCharHelper }

function TPPCharHelper.toArray: TStringArray;
var
  i: integer;
  cursor: PPChar;
begin
  Result := nil;
  if Self = nil then Exit;
  cursor := Self;
  i := 0;
  while cursor^ <> nil do
  begin
    SetLength(Result, i + 1);
    Result[i] := StrPas(cursor^);
    Inc(cursor);
    Inc(i);
  end;
end;

function TPPCharHelper.toArray(size: uint32): TStringArray;
var
  i: integer;
  pp: PPChar;
begin
  SetLength(Result, size);
  pp := Self;
  for i := 0 to size - 1 do
  begin
    if pp^ = nil then
      Result[i] := ''
    else
      Result[i] := StrPas(pp^);
    Inc(pp);
  end;
end;

{ Matrice & Vettori helper functions }

function Vec2(const x, y: single): TVec2;
begin
  Result := TVec2.Create(x, y);
end;

function Vec3(const x, y, z: single): TVec3;
begin
  Result := TVec3.Create(x, y, z);
end;

class function TVec3.Create(const ax, ay, az: single): TVec3;
begin
  Result.x := ax;
  Result.y := ay;
  Result.z := az;
end;

class operator TVec3.+(const a, b: TVec3): TVec3;
begin
  Result.x := a.x + b.x;
  Result.y := a.y + b.y;
  Result.z := a.z + b.z;
end;

class operator TVec3.-(const a, b: TVec3): TVec3;
begin
  Result.x := a.x - b.x;
  Result.y := a.y - b.y;
  Result.z := a.z - b.z;
end;

class operator TVec3.*(const v: TVec3; s: single): TVec3;
begin
  Result.x := v.x * s;
  Result.y := v.y * s;
  Result.z := v.z * s;
end;

function Vec4(const x, y, z, w: single): TVec4;
begin
  Result.x := x;
  Result.y := y;
  Result.z := z;
  Result.w := w;
end;

function Mat4Identity: TMat4;
begin
  FillChar(Result, SizeOf(Result), 0);
  Result.m[0, 0] := 1;
  Result.m[1, 1] := 1;
  Result.m[2, 2] := 1;
  Result.m[3, 3] := 1;
end;

function Mat4Translate(const m: TMat4; const v: TVec3): TMat4;
begin
  Result := m;
  Result.m[3, 0] := Result.m[3, 0] + v.x;
  Result.m[3, 1] := Result.m[3, 1] + v.y;
  Result.m[3, 2] := Result.m[3, 2] + v.z;
end;

function Mat4Rotate(const m: TMat4; angleRad: single; const axis: TVec3): TMat4;
var
  c, s, t: single;
  ux, uy, uz: single;
  rot: TMat4;
begin
  c := Cos(angleRad);
  s := Sin(angleRad);
  t := 1 - c;
  ux := axis.x;
  uy := axis.y;
  uz := axis.z;

  FillChar(rot, SizeOf(rot), 0);
  rot.m[0, 0] := t * ux * ux + c;
  rot.m[0, 1] := t * ux * uy - s * uz;
  rot.m[0, 2] := t * ux * uz + s * uy;
  rot.m[1, 0] := t * uy * ux + s * uz;
  rot.m[1, 1] := t * uy * uy + c;
  rot.m[1, 2] := t * uy * uz - s * ux;
  rot.m[2, 0] := t * uz * ux - s * uy;
  rot.m[2, 1] := t * uz * uy + s * ux;
  rot.m[2, 2] := t * uz * uz + c;
  rot.m[3, 3] := 1;

  Result := rot * m;
end;

function Mat4Scale(const m: TMat4; const v: TVec3): TMat4;
begin
  Result := m;
  Result.m[0, 0] := Result.m[0, 0] * v.x;
  Result.m[1, 1] := Result.m[1, 1] * v.y;
  Result.m[2, 2] := Result.m[2, 2] * v.z;
end;

function Mat4Perspective(fovyDeg: single; aspect: single; zNear, zFar: single): TMat4;
var
  tanHalfFovy: single;
begin
  FillChar(Result, SizeOf(Result), 0);
  tanHalfFovy := Tan(fovyDeg * DegToRad / 2);
  Result.m[0, 0] := 1 / (aspect * tanHalfFovy);
  Result.m[1, 1] := 1 / tanHalfFovy;
  Result.m[2, 2] := zFar / (zFar - zNear);
  Result.m[2, 3] := -1;
  Result.m[3, 2] := -(zFar * zNear) / (zFar - zNear);
  Result.m[3, 3] := 0;
end;

function Cross(const a, b: TVec3): TVec3;
begin
  Result.x := a.y * b.z - a.z * b.y;
  Result.y := a.z * b.x - a.x * b.z;
  Result.z := a.x * b.y - a.y * b.x;
end;

function Dot(const a, b: TVec3): single;
begin
  Result := a.x * b.x + a.y * b.y + a.z * b.z;
end;

function Normalize(const v: TVec3): TVec3;
var
  len: single;
begin
  len := Sqrt(Dot(v, v));
  if len > 0 then
  begin
    Result.x := v.x / len;
    Result.y := v.y / len;
    Result.z := v.z / len;
  end
  else
    Result := v;
end;

function Mat4LookAt(const eye, center, up: TVec3): TMat4;
var
  f, s, u: TVec3;
begin
  f := Normalize(center - eye);
  s := Normalize(Cross(f, up));
  u := Cross(s, f);

  Result := Mat4Identity;
  Result.m[0, 0] := s.x;
  Result.m[0, 1] := s.y;
  Result.m[0, 2] := s.z;
  Result.m[1, 0] := u.x;
  Result.m[1, 1] := u.y;
  Result.m[1, 2] := u.z;
  Result.m[2, 0] := -f.x;
  Result.m[2, 1] := -f.y;
  Result.m[2, 2] := -f.z;

  Result.m[3, 0] := -Dot(s, eye);
  Result.m[3, 1] := -Dot(u, eye);
  Result.m[3, 2] := Dot(f, eye);
end;

{ Operatori TMat4 }

class operator TMat4.*(const a, b: TMat4): TMat4;
var
  i, j, k: integer;
begin
  for i := 0 to 3 do
    for j := 0 to 3 do
    begin
      Result.m[i, j] := 0;
      for k := 0 to 3 do
        Result.m[i, j] := Result.m[i, j] + a.m[i, k] * b.m[k, j];
    end;
end;

class operator TMat4.*(const mat: TMat4; const v: TVec4): TVec4;
begin
  Result.x := mat.m[0, 0] * v.x + mat.m[1, 0] * v.y + mat.m[2, 0] * v.z + mat.m[3, 0] * v.w;
  Result.y := mat.m[0, 1] * v.x + mat.m[1, 1] * v.y + mat.m[2, 1] * v.z + mat.m[3, 1] * v.w;
  Result.z := mat.m[0, 2] * v.x + mat.m[1, 2] * v.y + mat.m[2, 2] * v.z + mat.m[3, 2] * v.w;
  Result.w := mat.m[0, 3] * v.x + mat.m[1, 3] * v.y + mat.m[2, 3] * v.z + mat.m[3, 3] * v.w;
end;

function TMat4.Element(row, col: integer): single;
begin
  Result := m[row, col];
end;

procedure TMat4.SetElement(row, col: integer; Value: single);
begin
  m[row, col] := Value;
end;

function TMat4.ToString: string;
var
  i, j: integer;
begin
  Result := '';
  for i := 0 to 3 do
  begin
    for j := 0 to 3 do
      Result := Result + Format('%8.3f ', [m[i, j]]);
    Result := Result + LineEnding;
  end;
end;

class function TVec2.Create(const ax, ay: single): TVec2;
begin
  Result.x := ax;
  Result.y := ay;
end;

class function TVec2.Zero: TVec2;
begin
  Result.x := 0;
  Result.y := 0;
end;

class operator TVec2.+(const a, b: TVec2): TVec2;
begin
  Result.x := a.x + b.x;
  Result.y := a.y + b.y;
end;

class operator TVec2.-(const a, b: TVec2): TVec2;
begin
  Result.x := a.x - b.x;
  Result.y := a.y - b.y;
end;

class operator TVec2.*(const v: TVec2; s: single): TVec2;
begin
  Result.x := v.x * s;
  Result.y := v.y * s;
end;

class operator TVec2.*(const a, b: TVec2): TVec2;
begin
  Result.x := a.x * b.x;
  Result.y := a.y * b.y;
end;

class operator TVec2./(const v: TVec2; s: single): TVec2;
begin
  Result.x := v.x / s;
  Result.y := v.y / s;
end;

class operator TVec2.-(const v: TVec2): TVec2;
begin
  Result.x := -v.x;
  Result.y := -v.y;
end;

function TVec2.Length: single;
begin
  Result := Sqrt(x * x + y * y);
end;

function TVec2.LengthSquared: single;
begin
  Result := x * x + y * y;
end;

function TVec2.Normalized: TVec2;
var
  len: single;
begin
  len := Length;
  if len > 0 then
    Result := Self / len
  else
    Result := Self;
end;

function TVec2.Dot(const other: TVec2): single;
begin
  Result := x * other.x + y * other.y;
end;

function TVec2.Perpendicular: TVec2;
begin
  Result.x := -y;
  Result.y := x;
end;

function TVec2.ToString: string;
begin
  Result := Format('(%0.4f, %0.4f)', [x, y]);
end;


initialization

  TutorialLogger := TLogger.Create;
  TutorialLogger.AddAppender(TFileAppender.Create(ChangeFileExt(ParamStr(0), '.log'), llTrace));
  TutorialLogger.AddAppender(TConsoleAppender.Create(llDebug));

finalization;

  TutorialLogger.Free;

end.
